### ISSUE TITLE
Remove as much white space as possible

### ISSUE THREAD

**Issue by jacksadler** [quirkles/roscr-coming-soon#10]
The white space still bothers me so just putting it out there to see if anything can be done about it. I reckon we can reduce or remove the white space around the 3 images for Connect Contribute, Collect. 

Do you think it would be possible to display the text outside of the white space and only the image in the white space? (ideally the white space would be round to match the shape of the image). 

This would get rid of the big white blocks, and we could make the 3 images larger.

Take a look at this ridiculously crude mock-up (the less white space, the better in my opinion):

![white space image](https://cloud.githubusercontent.com/assets/17211330/13616884/c6915ee2-e549-11e5-843e-d3a87fa23add.png)

**Comment by quirkles** [comment]
@jacksadler attached two mockups, let me know if you want to go with either of them, i have a prefernece but ill wait to hear what you think so i dont bias you. Bother are just as easy to implement
![2016-03-08 18_45_46-program manager](https://cloud.githubusercontent.com/assets/5017593/13620518/7310aa60-e55e-11e5-8acd-6518a44a470d.png)
![2016-03-08 18_47_13-program manager](https://cloud.githubusercontent.com/assets/5017593/13620519/73115550-e55e-11e5-9e05-77da26fedb51.png)

**Comment by quirkles** [comment]
also, looks good witth a bit more vertical spacing
![2016-03-08 18_49_50-program manager](https://cloud.githubusercontent.com/assets/5017593/13620552/ac8a56f6-e55e-11e5-92b4-a822813a6c04.png)

**Comment by jacksadler** [comment]
Great job man thats exactly what i was hoping for. I really like the 1st
one with white circles.

Also: i prefer the campfire picture to the forest picture

**Comment by jacksadler** [comment]
And yeah agreed on the verticle spacing. Using the screen a bit more.

**Comment by quirkles** [comment]
Changes have beben pushed tot he live site. Marking as closed
