### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jacksadler** [quirkles/roscr-coming-soon#9]
This might remain a work in progress until we all like the images.

I like the campfire one you have up and think we should keep it.

I put 3 more in the below location, let me know if you think they'd look good behind the ROSCr page
https://drive.google.com/drive/folders/0Byz-dKi06ORfTi1yV2ZVeUVyTk0

**Comment by quirkles** [comment]
![2016-02-26 21_34_35-greenshot](https://cloud.githubusercontent.com/assets/5017593/13370277/f60dd082-dcd0-11e5-8173-8f1295f096ce.png)
![2016-02-26 21_34_52-greenshot](https://cloud.githubusercontent.com/assets/5017593/13370278/f60e3d38-dcd0-11e5-80f3-1ffed72b7c1f.png)
![2016-02-26 21_35_01-greenshot](https://cloud.githubusercontent.com/assets/5017593/13370279/f60ef782-dcd0-11e5-8022-e66b28d8fc70.png)

@jacksadler I think they are too light, the sun in that image obscures everything else too

**Comment by jacksadler** [comment]
Yeah, agreed. I'll keep looking. You get the theme im after right? People
on  acation basically, cos they saved so much money!!
